name: CI

on:
  # Triggers the workflow on push or pull request events but only for the "main" branch
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: create an issue with the github token
        env:
          GH_TOKEN: ${{ github.token }}
        run: gh issue create --title "I found a bug" --body "Nothing works" -R ${{ github.repository }}

      - uses: actions/create-github-app-token@v1
        id: app-token
        with:
          app-id: ${{ vars.APP_ID }}
          private-key: ${{ secrets.PRIVATE_KEY }}

      - name: create an issue with the app's auth
        env:
          GH_TOKEN: ${{ steps.app-token.outputs.token }}
        run: |
          echo Add other actions to build,
          gh issue create --title "I found a bug, but with an app!" --body "Nothing works" -R ${{ github.repository }}
